group=dev.typr
version=1.0.0-M1

scala2Version=2.13.16
scala3Version=3.3.4

hikariVersion=6.2.1
springVersion=6.2.2
springBootVersion=3.4.1
jetbrainsAnnotationsVersion=26.0.1
junitVersion=4.13.2
testcontainersVersion=1.20.4

postgresqlDriverVersion=42.7.3
mariadbDriverVersion=3.5.1
duckdbDriverVersion=1.1.3
oracleDriverVersion=23.6.0.24.10
sqlserverDriverVersion=12.8.1.jre11
db2DriverVersion=11.5.9.0

kotlin.daemon.jvmargs=-Xmx4g
